# Generated by Django 3.1.7 on 2021-03-31 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hello.register', to_field='username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address1',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='fullAddress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hello.profile', to_field='address1'),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
