# Generated by Django 3.1.7 on 2021-04-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_remove_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska')], max_length=2),
        ),
    ]
