# Generated by Django 3.1.7 on 2021-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20210419_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hasHistory',
            field=models.BooleanField(default=False),
        ),
    ]
